- title: Advanced Web Hacking
  trainers: Dhruv Shah and Sunil Yadav (NotSoSecure)
  duration: 3 Days
  days: Sun/Mon/Tue
  localprice: 10250 NIS
  price: $2400
- title: Attacking and Defending Containerized Apps  and Serverless Tech
  trainers: Nithin Jois (we45)
  duration: 3 Days
  days: Sun/Mon/Tue
  localprice: 10250 NIS
  price: $2400
- title: DevSecOps MasterClass
  trainers: Abhay Bhargav (we45)
  duration: 3 Days
  days: Sun/Mon/Tue
  localprice: 10250 NIS
  price: $2400
- title: Advanced Whiteboard hacking – aka hands-on  Threat Modeling
  trainers: Steven Wierckx (Toreon)
  duration: 2 Days
  days: Mon/Tue
  localprice: 7050 NIS
  price: $1650
- title: An Introduction to Hacking Blockchain  Applications and Smart Contracts
  trainers: Mick Ayzenberg (Security Innovation)
  duration: 2 Days
  days: Mon/Tue
  localprice: 7050 NIS
  price: $1650
- title: Hands-on Secure Coding in Node.js
  trainers: Chetan Karande
  duration: 2 Days
  days: Mon/Tue
  localprice: 7050 NIS
  price: $1650
- title: Mastering Secure coding and web-application  security testing
  trainers: Glenn ten Cate (DefDev.eu)
  duration: 2 Days
  days: Mon/Tue
  localprice: 7050 NIS
  price: $1650
- title: "Program Building: Navigating Your First  Year As A First Time CISO"
  trainers: Robert Wood
  duration: 2 Days
  days: Mon/Tue
  localprice: 7050 NIS
  price: $1650
- title: Seth & Ken’s Excellent Adventures (in Code Review)
  trainers: Ken Johnson and Seth Law
  duration: 2 Days
  days: Mon/Tue
  localprice: 7050 NIS
  price: $1650
- title: Modern iOS App Exploitation
  trainers: Swaroop Yermalkar
  duration: 1 Day
  days: Mon
  localprice: 3630 NIS
  price: $850
- title: Modern Android App Exploitation
  trainers: Arun Thomas
  duration: 1 Day
  days: Tue
  localprice: 3630 NIS
  price: $850
- title: Defending Golang
  trainers: Mike Doyle (Synopsys)
  duration: 1 Day
  days: Tue
  localprice: 3630 NIS
  price: $850
  - title: Web Application Hacking with Burp Suite and OWASP ZAP (Women Only)
    trainers: Vandana Verma
    duration: 1 Day
    days: Tue
    localprice: FREE
    price: FREE
